SET DB_CLOSE_DELAY -1;         
;              
CREATE USER IF NOT EXISTS "SA" SALT 'd6c83f1e68a99d24' HASH 'de94ac5768bf01b7a442cf1cfc09dc581324a41213d295671db8d62a20afbe7c' ADMIN;          
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_0B28B886_2ADF_49E8_9FD9_5DD9C4B5ED73" START WITH 1 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_AEA1EE69_D784_4E27_9D39_294327705DBB" START WITH 1 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_144A3398_640E_47CF_AFB9_380D6734BF27" START WITH 1 BELONGS_TO_TABLE; 
CREATE MEMORY TABLE "PUBLIC"."DEPARTMENT"(
    "DEPARTMENT_ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_AEA1EE69_D784_4E27_9D39_294327705DBB" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_AEA1EE69_D784_4E27_9D39_294327705DBB",
    "DEPARTMENT_NAME" VARCHAR(50)
);          
ALTER TABLE "PUBLIC"."DEPARTMENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("DEPARTMENT_ID");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DEPARTMENT;               
CREATE MEMORY TABLE "PUBLIC"."EMPLOYEE"(
    "EMPLOYEE_ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_144A3398_640E_47CF_AFB9_380D6734BF27" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_144A3398_640E_47CF_AFB9_380D6734BF27",
    "EMPLOYEE_AGE" INTEGER NOT NULL,
    "EMPLOYEE_BIRTHDAY" DATE,
    "EMPLOYEE_DOCUMENT" VARCHAR(50),
    "EMPLOYEE_NAME" VARCHAR(50),
    "POSITION_ID" INTEGER
);
ALTER TABLE "PUBLIC"."EMPLOYEE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("EMPLOYEE_ID");             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.EMPLOYEE; 
CREATE MEMORY TABLE "PUBLIC"."EMPLOYEE_DEPARTMENT"(
    "DEPARTMENT_ID" INTEGER NOT NULL,
    "EMPLOYEE_ID" INTEGER NOT NULL
);
ALTER TABLE "PUBLIC"."EMPLOYEE_DEPARTMENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("DEPARTMENT_ID", "EMPLOYEE_ID"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.EMPLOYEE_DEPARTMENT;      
CREATE MEMORY TABLE "PUBLIC"."HISTORY_EMPLOYEE_POSITION"(
    "EMPLOYEE_ID" INTEGER NOT NULL,
    "POSITION_ID" INTEGER NOT NULL
);            
ALTER TABLE "PUBLIC"."HISTORY_EMPLOYEE_POSITION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("EMPLOYEE_ID", "POSITION_ID");             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HISTORY_EMPLOYEE_POSITION;
CREATE MEMORY TABLE "PUBLIC"."POSITION"(
    "POSITION_ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_0B28B886_2ADF_49E8_9FD9_5DD9C4B5ED73" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_0B28B886_2ADF_49E8_9FD9_5DD9C4B5ED73",
    "IS_BOSS" BOOLEAN NOT NULL,
    "POSITION_NAME" VARCHAR(50)
);
ALTER TABLE "PUBLIC"."POSITION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("POSITION_ID");             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.POSITION; 
ALTER TABLE "PUBLIC"."EMPLOYEE_DEPARTMENT" ADD CONSTRAINT "PUBLIC"."UK_6AYHBP88GXNM4GN0RL2JGRPGO" UNIQUE("EMPLOYEE_ID");       
ALTER TABLE "PUBLIC"."EMPLOYEE_DEPARTMENT" ADD CONSTRAINT "PUBLIC"."FK6NJTIPGQOUU9AX631VMW9XLRA" FOREIGN KEY("EMPLOYEE_ID") REFERENCES "PUBLIC"."EMPLOYEE"("EMPLOYEE_ID") NOCHECK;             
ALTER TABLE "PUBLIC"."HISTORY_EMPLOYEE_POSITION" ADD CONSTRAINT "PUBLIC"."FKFVQPX2HF2KS1E762NSMT02DRS" FOREIGN KEY("POSITION_ID") REFERENCES "PUBLIC"."POSITION"("POSITION_ID") NOCHECK;       
ALTER TABLE "PUBLIC"."HISTORY_EMPLOYEE_POSITION" ADD CONSTRAINT "PUBLIC"."FK8RL8HN0SOF886RV3KCAAENQIW" FOREIGN KEY("EMPLOYEE_ID") REFERENCES "PUBLIC"."EMPLOYEE"("EMPLOYEE_ID") NOCHECK;       
-- ALTER TABLE "PUBLIC"."EMPLOYEE" ADD CONSTRAINT "PUBLIC"."FKBEJTWVG9BXUS2MFFSM3SWJ3U9" FOREIGN KEY("DEPARTMENT_ID") REFERENCES "PUBLIC"."DEPARTMENT"("DEPARTMENT_ID") NOCHECK;
ALTER TABLE "PUBLIC"."EMPLOYEE_DEPARTMENT" ADD CONSTRAINT "PUBLIC"."FKSU8J44UXLGH4LG6QWOMYEYEJL" FOREIGN KEY("DEPARTMENT_ID") REFERENCES "PUBLIC"."DEPARTMENT"("DEPARTMENT_ID") NOCHECK;       
ALTER TABLE "PUBLIC"."EMPLOYEE" ADD CONSTRAINT "PUBLIC"."FKBC8RDKO9O9N1RI9BPDYXV3X7I" FOREIGN KEY("POSITION_ID") REFERENCES "PUBLIC"."POSITION"("POSITION_ID") NOCHECK;        


-- INSERTS

INSERT INTO "PUBLIC"."POSITION"(POSITION_ID,POSITION_NAME,IS_BOSS)
VALUES (1,'Administrador de Redes',0), (2,'Gerente TI',1), (3,'Atendente',0);

INSERT INTO "PUBLIC"."EMPLOYEE"(EMPLOYEE_ID,EMPLOYEE_NAME,EMPLOYEE_AGE,EMPLOYEE_BIRTHDAY,EMPLOYEE_DOCUMENT,POSITION_ID)
VALUES (1,'Bob',20,'2001-05-07','0000',2), (2,'Ana',25,'1996-04-12','1111',1);

INSERT INTO "PUBLIC"."DEPARTMENT"(DEPARTMENT_ID,DEPARTMENT_NAME)
VALUES (1,'Comercial'), (2,'Financeiro');

INSERT INTO "PUBLIC"."EMPLOYEE_DEPARTMENT"(DEPARTMENT_ID,EMPLOYEE_ID)
VALUES (1,1), (1,2);

INSERT INTO "PUBLIC"."HISTORY_EMPLOYEE_POSITION"(EMPLOYEE_ID,POSITION_ID)
VALUES (1,1);