version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3341:3306"
    volumes:
    - cardif_data:/var/lib/mysql

volumes:
  cardif_data:
